---
- name: CDBURNERXP
  hosts: all
  gather_facts: yes
  vars:
    the_icon: 'C:\Users\Public\Desktop\CDBurnerXP.lnk'

  tasks:
    - name: CDBURNERXP - install cdburnerxp using chocolatey
      win_chocolatey:
        name: cdburnerxp
        state: present

    - name: CDBURNERXP - remove desktop link if present
      win_file:
        path: '{{ the_icon }}'
        state: absent
