---
- name: EVERYTHING
  hosts: all
  gather_facts: yes
  vars:
    everything_conf_ini: '{{ ansible_facts.env.APPDATA }}\EVERYTHING'

  tasks:
    - name: EVERYTHING - install everything using chocolatey
      win_chocolatey:
        name: everything
        state: present

    - name: EVERYTHING - copy the config file
      win_copy:
        src: Everything.ini
        dest: '{{ everything_conf_ini }}'

