---
- name: IRFANVIEW
  hosts: all
  gather_facts: yes
  vars:
    irfan_programfiles_lang: 'C:\Program Files\IrfanView\Languages'
    irfan_programfiles_plugins: 'C:\Program Files\IrfanView\Plugins'
    irfan_config_dir: '{{ ansible_facts.env.APPDATA }}\IrfanView'

  tasks:
    - name: IRFANVIEW - install irfanview using chocolatey
      win_chocolatey:
        name: irfanview
        state: present

    - name: IRFANVIEW - copy langauge files in to programfiles folder
      win_copy:
        src: '{{ item }}'
        dest: '{{ irfan_programfiles_lang }}'
      loop:
        - IP_Slovak.lng
        - Slovak.dll

    - name: IRFANVIEW - copy webp plugin in to programfiles
      win_copy:
        src: WebP.dll
        dest: '{{ irfan_programfiles_plugins }}'

    - name: IRFANVIEW - copy config ini file in to appdata
      win_copy:
        src: i_view64.ini
        dest: '{{ irfan_config_dir }}'


